import Vue from "vue";
import {
  AddressList,
  AddressEdit,
  Toast,
  Swipe,
  SwipeItem,
  Lazyload,
  CouponCell,
  CouponList,
  Popup,
  Icon,
  Form,
  Field,
  Radio,
  Button,
  Tabbar,
  TabbarItem,
  Popover,
  Skeleton,
  Tab,
  Tabs,
  Checkbox,
  CheckboxGroup,
  Stepper,
  Search,
  Divider,
  Empty,
  GoodsAction,
  GoodsActionIcon,
  GoodsActionButton,
} from "vant";

Vue.use(AddressList);
Vue.use(AddressEdit);
Vue.use(Toast);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Lazyload);
Vue.use(AddressList);
Vue.use(Toast);
Vue.use(CouponCell);
Vue.use(CouponList);
Vue.use(Popup);
Vue.use(Icon);
Vue.use(Form);
Vue.use(Radio);
Vue.use(Field);
Vue.use(Button);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Popover);
Vue.use(Skeleton);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Stepper);
Vue.use(Search);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Divider);
Vue.use(Empty);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
